# Driver for the packaging regression test (run by ctest as cmake -P).
#
# 1. installs slick-dynamic-buffer from the parent build tree into a scratch prefix
# 2. configures and builds tests/install_consumer against that prefix, with the
#    consumer asking for C++17 - it only compiles if the installed target raises
#    the requirement to C++20
# 3. runs the consumer, which checks the boundary behaviour of the installed header
#
# Cost control: the parent build tree is installed directly rather than configured a
# second time, and the consumer build tree is reused between runs (a cold configure with
# a toolchain file costs far more than the compile being tested). A stale or unusable
# consumer cache is detected and rebuilt from scratch, so reuse cannot mask a failure.
#
# Required -D arguments: PARENT_BUILD_DIR CONSUMER_DIR WORK_DIR BUILD_CONFIG
# Optional: CTEST_EXECUTABLE GENERATOR GENERATOR_PLATFORM GENERATOR_TOOLSET
#           MAKE_PROGRAM TOOLCHAIN_FILE PREFIX_PATH

cmake_minimum_required(VERSION 3.21)

foreach(_required PARENT_BUILD_DIR CONSUMER_DIR WORK_DIR BUILD_CONFIG)
    if("${${_required}}" STREQUAL "")
        message(FATAL_ERROR "install_and_consume.cmake: -D${_required} is required")
    endif()
endforeach()

set(_prefix "${WORK_DIR}/prefix")
set(_consumer_build "${WORK_DIR}/consumer-build")

file(MAKE_DIRECTORY "${WORK_DIR}")

# Reproduce the parent build environment, otherwise the consumer configure can pick a
# different generator or fail to find Boost.
set(_common_args)
if(GENERATOR)
    list(APPEND _common_args -G "${GENERATOR}")
endif()
if(GENERATOR_PLATFORM)
    list(APPEND _common_args -A "${GENERATOR_PLATFORM}")
endif()
if(GENERATOR_TOOLSET)
    list(APPEND _common_args -T "${GENERATOR_TOOLSET}")
endif()
if(MAKE_PROGRAM)
    list(APPEND _common_args "-DCMAKE_MAKE_PROGRAM=${MAKE_PROGRAM}")
endif()
if(TOOLCHAIN_FILE)
    list(APPEND _common_args "-DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_FILE}")
endif()
list(APPEND _common_args "-DCMAKE_BUILD_TYPE=${BUILD_CONFIG}")

# Commands are passed by variable NAME, never by value. An argument holding an escaped
# ';' (the consumer CMAKE_PREFIX_PATH below) is unescaped the moment the list is expanded,
# so forwarding a command through ARGN would flatten it and turn the extra search paths
# into stray positional arguments. Dereferencing the name keeps it to a single expansion.
function(try_step result_var description command_var)
    message(STATUS "install test: ${description}")
    execute_process(COMMAND ${${command_var}} RESULT_VARIABLE _result)
    set(${result_var} "${_result}" PARENT_SCOPE)
endfunction()

function(run_step description command_var)
    try_step(_rc "${description}" "${command_var}")
    if(NOT _rc EQUAL 0)
        message(FATAL_ERROR "install test: ${description} failed (exit code ${_rc})")
    endif()
endfunction()

# The install rules under test were already generated by the parent configure.
set(_install_package
    "${CMAKE_COMMAND}" --install "${PARENT_BUILD_DIR}"
    --config "${BUILD_CONFIG}" --prefix "${_prefix}")
run_step("install slick-dynamic-buffer into the scratch prefix" _install_package)

# Keep the prefix hermetic without wiping it: cmake --install leaves unchanged files
# byte-identical and untouched, so anything the fresh manifest does not mention is a
# leftover from an earlier run and would otherwise mask a removed or renamed file.
# (Wiping instead would change every timestamp and force a full consumer re-configure.)
set(_manifest "${PARENT_BUILD_DIR}/install_manifest.txt")
if(EXISTS "${_manifest}")
    set(_installed)
    file(STRINGS "${_manifest}" _manifest_lines)
    foreach(_line IN LISTS _manifest_lines)
        file(TO_CMAKE_PATH "${_line}" _line)
        list(APPEND _installed "${_line}")
    endforeach()
    file(GLOB_RECURSE _present "${_prefix}/*")
    foreach(_file IN LISTS _present)
        if(NOT _file IN_LIST _installed)
            message(STATUS "install test: removing stale ${_file}")
            file(REMOVE "${_file}")
        endif()
    endforeach()
endif()

# A command is held in a list variable here, and a list element containing a bare ';' is
# indistinguishable from the list separator: expanding the command would turn every path
# after the first into a stray positional argument ("Ignoring extra path from command
# line") and silently drop it from the consumer CMAKE_PREFIX_PATH. Escape the separators
# so the whole search path survives as one argument.
set(_consumer_prefix_paths "${_prefix}")
if(NOT "${PREFIX_PATH}" STREQUAL "")
    list(APPEND _consumer_prefix_paths ${PREFIX_PATH})
endif()
string(REPLACE ";" "\\;" _consumer_prefix_path "${_consumer_prefix_paths}")

# The consumer sets CMAKE_CXX_STANDARD 17; find_package must supply the rest.
# slick-dynamic-buffer_DIR pins the lookup to the scratch prefix. The vcpkg toolchain
# prepends its own installed tree to CMAKE_PREFIX_PATH, so an already-installed copy of
# this package shadows the one under test unless the config location is given outright.
set(_configure_consumer
    "${CMAKE_COMMAND}" -S "${CONSUMER_DIR}" -B "${_consumer_build}" ${_common_args}
    "-Dslick-dynamic-buffer_DIR=${_prefix}/lib/cmake/slick-dynamic-buffer"
    "-Dslick-dynamic-buffer_ROOT=${_prefix}"
    "-DEXPECTED_PACKAGE_PREFIX=${_prefix}"
    "-DCMAKE_PREFIX_PATH=${_consumer_prefix_path}")

# Configuring the consumer costs more than the compile it exists to check, so do it only
# when there is no usable cache or the arguments changed. When the installed package
# itself changes, the build step below re-runs cmake on its own: the package config files
# are inputs to the generated build system, exactly like the CMakeLists.
set(_stamp "${_consumer_build}/configure-args.txt")
set(_configured FALSE)
if(EXISTS "${_consumer_build}/CMakeCache.txt" AND EXISTS "${_stamp}")
    file(READ "${_stamp}" _previous_args)
    if(_previous_args STREQUAL "${_configure_consumer}")
        set(_configured TRUE)
        message(STATUS "install test: reusing the configured consumer build tree")
    endif()
endif()

if(NOT _configured)
    try_step(_rc "configure C++17 consumer against the installed package" _configure_consumer)
    if(NOT _rc EQUAL 0)
        # A cache left by an earlier run can be unusable (different generator, moved paths).
        file(REMOVE_RECURSE "${_consumer_build}")
        run_step("re-configure C++17 consumer from a clean build tree" _configure_consumer)
    endif()
    file(WRITE "${_stamp}" "${_configure_consumer}")
endif()

# Guard the quoting above: when the search path is flattened, CMake reports "Ignoring
# extra path from command line" and drops the entries, and the test then passes only
# because something else (a toolchain file) happened to supply them.
file(STRINGS "${_consumer_build}/CMakeCache.txt" _cached_prefix_path REGEX "^CMAKE_PREFIX_PATH")
foreach(_path IN LISTS _consumer_prefix_paths)
    string(FIND "${_cached_prefix_path}" "${_path}" _found)
    if(_found LESS 0)
        message(FATAL_ERROR
            "install test: ${_path} did not survive into the consumer CMAKE_PREFIX_PATH "
            "(cache has: ${_cached_prefix_path})")
    endif()
endforeach()

set(_build_consumer
    "${CMAKE_COMMAND}" --build "${_consumer_build}" --config "${BUILD_CONFIG}")
run_step("build consumer" _build_consumer)

if(CTEST_EXECUTABLE)
    set(_run_consumer
        "${CTEST_EXECUTABLE}" --test-dir "${_consumer_build}" -C "${BUILD_CONFIG}"
        --output-on-failure)
    run_step("run consumer" _run_consumer)
endif()
